name: Python application

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync --categories "packages http"
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
        dpkg -i cloudflared.deb

    - name: Start services
      shell: bash
      env:
        CF_TUNNEL_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}
      run: cloudflared service install $CF_TUNNEL_TOKEN & python inference_server.py